### ISSUE TITLE
I know this might be dead, but...

### ISSUE THREAD

**Issue by varmint09** [themusicman/Sherlock#2]
Hello,

I have been using this plugin with the latest version of EE, and I also use simple pagination, I have the following structure.

/{channel}

Shows all entries in all channel categories (paginated)

/{channel}/{category}

Shows all entries in that channel category (paginated)

/{channel}/{category}/{entry_url_title}

Shows the entry

------ EVERYTHING ABOVE THIS LINE WORKS ------

I now want to split long articles over several pages, and if I have the following;

/{channel}/{category}/{entry_url_title}/{pagination} where pagination is like P2

Sherlock tells me the page is not an entry!

How so?

tags used...

 {exp:sherlock:page_type entry_title_segments="3"}

{if is_pagination}is pagination{/if}
{if is_not_pagination}is not pagination{/if}
{if is_listing}is listing{/if}
{if is_not_listing}is not listing{/if}
{if is_category}is category{/if}
{if is_not_category}is not category{/if}
{if is_entry}is entry{/if}
{if is_not_entry}is not entry{/if}

**Comment by themusicman** [comment]
Right now it sets a page as an entry if it is not a listing and part of the logic for if it is a listing is if it has pagination.  Let me alter the logic to allow for pagination on both entry and listing pages.  It might be a couple days before I can get to it.

**Comment by varmint09** [comment]
I am using this, which works but seems clumsy... but seems to work



 {exp:sherlock:page_type entry_title_segments="3"}

        {if is_listing && is_not_category && segment_4 == false}

           show all entries in channel and paginate

       {if:elseif is_category && is_listing && segment_4 == false}

          show all in category

       {if:elseif segment_4 || is_entry}

         show entry

       {if:elseif is_not_category && is_entry}
         do redirect back to /{channel} 
      {/if}

{/exp:sherlock:page_type}

**Comment by varmint09** [comment]
Your suggestion makes sense, and honestly your plugin was the whole reason I was able to have my site in Expression Engine, it will be great if it could be improved once more.

Last suggestion is to place the code in a /system/expressionengine/third_party/ structure so it worked with the Updater plugin.

Many thanks - or I might PR that last bit if its a hassle.

**Comment by themusicman** [comment]
Just made a few commits that should fix the conditional issue and add Updater compat. Can you give it a try and see if it works for you?

**Comment by varmint09** [comment]
Thanks, works great now. You should bump the version etc for people to know.

This is a very useful add on, so glad this has been improved, even if the EE ecosystem feels like its dying  out.

**Comment by themusicman** [comment]
I bumped it to 1.3.  Yeah, EE is still my company's main CMS, but when we can we use others like Craft and Locomotive.
