### ISSUE TITLE
What about EE3?

### ISSUE THREAD

**Issue by varmint09** [themusicman/Sherlock#3]
Hi,

Was pondering an upgrade to EE3, but I use Sherlock, is the functionality baked into EE3 or would I need to find another plugin solution... or is EE dead?

Thanks!

**Comment by themusicman** [comment]
I have added an EE3 branch here: https://github.com/themusicman/Sherlock/tree/ee3

Give it a try.  I have not spent enough time with EE3 yet to know if you will run into any problems.  I am pretty sure all the EE code will be fine though.  I think if you run into problems it will be with how EE3 structures its URLs.  Not sure if there are any changes there.  Create issues if you run into any problems.
